<?php

/*
 * Xibo - Digital Signage - http://www.xibo.org.uk
 *
 * This file is part of Xibo - and is automatically generated by the installer
 *
 * You should not need to edit this file, unless your SQL connection details have changed.
 */
defined ( 'XIBO' ) or die ( __ ( "Sorry, you are not allowed to directly access this page." ) . "<br />" . __ ( "Please press the back button in your browser." ) );
require_once ("globalVar.php");

/*
 * Layout configuration
 */
$dbhost = 'localhost';
$dbuser = 'xiboadm';
$dbpass = '1';
$dbname = 'xibodb';

// Array
// (
//     [[Basic]] => http://www.ssu.ac.kr/
//     [[Man]] => http://www.man.ac.kr/
//     [[Woman]] => http://www.woman.ac.kr/
//     [[Crowded]] => http://www.crowded.ac.kr/
// )
$nfcKeys = array (
		"[Basic]",
		"[Man]",
		"[Woman]",
		"[Crowded]"
);

$nfcURL = array (
		"http://www.ssu.ac.kr/",
		"http://www.man.ac.kr/",
		"http://www.woman.ac.kr/",
		"http://www.crowded.ac.kr/" 
);

for($i = 0; $i < count ( $nfcKeys ); $i ++) {
	$keys [$nfcKeys [$i]] = $nfcURL [$i];
}
